# .prettierrc.yml
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: "none"

# YAML specific settings
overrides:
  - files: "*.{yml,yaml}"
    options:
      tabWidth: 2
      printWidth: 120