name: New Control Proposal
description: Propose a new security control for the CoSAI Risk Map
title: '[Control]: '
labels: ['control', 'new-control']
body:
  - type: markdown
    attributes:
      value: |
        ## Propose a New Control
        Use this template to suggest a new security control for the AI risk framework.

        **Required fields** are marked with an asterisk (*).

  - type: input
    id: control-title
    attributes:
      label: Control Title*
      description: A concise, descriptive name for the control
      placeholder: 'e.g., Privacy Enhancing Technologies'
    validations:
      required: true

  - type: textarea
    id: control-description
    attributes:
      label: Control Description*
      description: Detailed explanation of what the control does and how it mitigates risks
      placeholder: "Describe the control's purpose, implementation approach, and expected outcomes..."
    validations:
      required: true

  - type: dropdown
    id: control-category
    attributes:
      label: Control Category*
      description: Primary category this control belongs to
      options:
        - controlsData
        - controlsInfrastructure
        - controlsModel
        - controlsApplication
        - controlsAssurance
        - controlsGovernance
    validations:
      required: true

  - type: checkboxes
    id: personas
    attributes:
      label: Applicable Personas*
      description: Which personas should implement this control?
      options:
        - label: personaModelCreator
        - label: personaModelConsumer

  - type: textarea
    id: components
    attributes:
      label: Applicable Components*
      description: |
        List component IDs this control applies to (one per line), or use "all" or "none"

        📋 [View full component list](../../risk-map/tables/components-summary.md)

        Common components: componentDataSources, componentTrainingData, componentModelServing, componentModelStorage, componentOutputHandling, etc.
      placeholder: |
        componentDataSources
        componentTrainingData
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Mitigated Risks*
      description: |
        List risk IDs this control addresses (one per line), or use "all"

        ✨ **Automatic Cross-Mapping**: When you map this control to risks, the reverse mappings are automatically created. Each risk you list here will automatically get this control added to its applicable controls.

        📋 [View full risk list](../../risk-map/tables/risks-summary.md)

        Common risks: DP (Data Poisoning), MST (Model Theft), PIJ (Prompt Injection), SDD (Sensitive Data Disclosure), etc.
      placeholder: |
        DP
        UTD
    validations:
      required: true

  - type: textarea
    id: external-mapping
    attributes:
      label: Framework Mappings (Optional)
      description: |
        Map this control to external security frameworks by listing relevant mitigation or control IDs.
        Enter one ID per line (no special formatting needed).

        Valid frameworks for controls include: mitre-atlas, nist-ai-rmf, owasp-top10-llm
      placeholder: |
        mitre-atlas AML.M0007
        nist-airmf GV-6.2

  - type: checkboxes
    id: lifecycle-stage
    attributes:
      label: Lifecycle Stages (Optional)
      description: Which AI system lifecycle phases does this control apply to?
      options:
        - label: planning
        - label: data-preparation
        - label: model-training
        - label: development
        - label: evaluation
        - label: deployment
        - label: runtime
        - label: maintenance

  - type: checkboxes
    id: impact-type
    attributes:
      label: Impact Types (Optional)
      description: What types of security/safety impacts does this control address?
      options:
        - label: confidentiality
        - label: integrity
        - label: availability
        - label: privacy
        - label: safety
        - label: compliance
        - label: fairness
        - label: accountability
        - label: reliability
        - label: transparency

  - type: checkboxes
    id: actor-access
    attributes:
      label: Actor Access Levels (Optional)
      description: What threat actor access levels does this control defend against?
      options:
        - label: external
        - label: api
        - label: user
        - label: privileged
        - label: agent
        - label: supply-chain
        - label: infrastructure-provider
        - label: service-provider
        - label: physical

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, use cases, or implementation considerations
      placeholder: 'Provide examples, related standards, implementation challenges, etc.'

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have reviewed existing controls to ensure this is not a duplicate
          required: true
        - label: I understand that reverse risk-to-control mappings will be automatically created
          required: true
        - label: I have provided all required fields marked with (*)
          required: true
        - label: The control aligns with the CoSAI Risk Map framework objectives
          required: true
