name: New Component Proposal
description: Propose a new AI system component for the CoSAI Risk Map
title: '[Component]: '
labels: ['component', 'new-component']
body:
  - type: markdown
    attributes:
      value: |
        ## Propose a New Component
        Use this template to suggest a new AI system component for the risk framework.

        **Required fields** are marked with an asterisk (*).

        ⚠️ **Important**: Component edges must be bidirectional. If you add `A → B`, then `B ← A` must also exist.

  - type: input
    id: component-id
    attributes:
      label: Component ID*
      description: |
        Unique identifier in camelCase format

        Must start with "component" (e.g., componentMyNewComponent)
      placeholder: 'e.g., componentPromptCache'
    validations:
      required: true

  - type: input
    id: component-title
    attributes:
      label: Component Title*
      description: A concise, human-readable name for the component
      placeholder: 'e.g., Prompt Cache'
    validations:
      required: true

  - type: textarea
    id: component-description
    attributes:
      label: Component Description*
      description: |
        Detailed explanation of what this component represents in the AI system

        Describe its purpose, role, and how it fits into the broader architecture
      placeholder: "Describe the component's function, purpose, and architectural role..."
    validations:
      required: true

  - type: dropdown
    id: component-category
    attributes:
      label: Component Category*
      description: Primary category this component belongs to
      options:
        - componentsInfrastructure (Infrastructure)
        - componentsModel (Model)
        - componentsApplication (Application)
    validations:
      required: true

  - type: dropdown
    id: component-subcategory
    attributes:
      label: Component Subcategory (Optional)
      description: Subcategory if applicable
      options:
        - N/A - No subcategory
        - componentsData (Data components)
        - componentsModelTraining (Model training components)
        - componentsAgent (Agent components)
        - componentsOrchestration (Orchestration components)

  - type: markdown
    attributes:
      value: |
        ---
        ## Component Relationships*

        Define how this component connects to other components in the system.

        ✨ **Automatic Bidirectionality**: When you specify edges, the reverse edges are automatically created.
        - If you add `componentB` in "Edges To", then `componentB` will automatically get an "Edges From" entry for this component
        - If you add `componentA` in "Edges From", then `componentA` will automatically get an "Edges To" entry for this component

        📋 [View component list](../../risk-map/tables/components-summary.md)

  - type: textarea
    id: edges-to
    attributes:
      label: Edges To (Downstream)*
      description: |
        Components that this component flows TO (one per line)

        These are components that receive data/control flow FROM this component
      placeholder: |
        componentOutputHandling
        componentModelServing
    validations:
      required: true

  - type: textarea
    id: edges-from
    attributes:
      label: Edges From (Upstream)*
      description: |
        Components that flow TO this component (one per line)

        These are components that send data/control flow TO this component
      placeholder: |
        componentInputHandling
        componentDataSources
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any additional information about this component

        Include use cases, examples, architectural diagrams, or implementation details
      placeholder: 'Provide examples, architectural context, related components, etc.'

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have reviewed existing components to ensure this is not a duplicate
          required: true
        - label: I understand that reverse edges will be automatically created for connected components
          required: true
        - label: I have provided all required fields marked with (*)
          required: true
        - label: The component aligns with the CoSAI Risk Map framework architecture
          required: true
