#!/bin/bash
set -e

# Install act for github workflow testing
echo "Installing act..."
wget -q https://raw.githubusercontent.com/nektos/act/master/install.sh -O install.sh
chmod +x install.sh
sudo ./install.sh -b /usr/local/bin
rm ./install.sh

echo "Setup complete"