name: Python Validation

on:
  push:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  ci-tools-validation:  
    runs-on: ubuntu-latest
    name: CI-CD Tool Validation  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    
    - name: Lint with Ruff
      run: |
        # Recursive check starting at repo root
        RUFF="ruff"
        RUFF_ARGS="check --output-format=github "

        if ! $(${RUFF} ${RUFF_ARGS}); then
          echo "   ❌ Python linting failed - check output"
          echo "::error::Python formatting validation failed"
          exit 1
        else
          echo "   ✅ All python files successfully passed linting"
        fi
      continue-on-error: true
    
    - name: Test Python
      run: |
        PYTHON_TEST_DIR="./test"

        pytest --junitxml=junit/test-results.xml

    - name: Validation Summary
      if: success()
      run: |
        echo "🎉 All secure-ai-tooling python validations completed successfully!"
        echo "  ✅ Python linting validation"
        echo "  ✅ Python test validation"
        echo ""
        echo "The secure-ai-tooling repository maintains full integrity and consistency."
